<CustomLabel@Label>:
    text_size: self.size
    valign: "middle"
    padding_x: 5

<SingleLineTextInput@TextInput>:
    multiline: False

<GreenButton@Button>:
    background_color: 4, 1, 3, 2
    size_hint_y: None
    height: self.parent.height * 0.120

UserGroup
    username: txt_username
    password: txt_password
    email: txt_email


    GridLayout:
        cols: 1
        padding : 30,30
        spacing: 20, 20
        row_default_height: '30dp'
        
        Image: 
            source: "login1.gif"
            size_hint_y: None
            height: 100
            valign: 'middle'

    GridLayout:
        cols: 1
        padding : 30,30
        spacing: 20, 20
        row_default_height: '30dp'
        
        Image: 
            source: "login.png"
            size_hint_y: None
            height: 200
            valign: 'middle'

    GridLayout:
        cols: 2
        padding : 30,30
        spacing: 20, 20
        row_default_height: '30dp'

        CustomLabel:
        	text: 'Username'
        	text_size: self.size
        	valign: 'middle'

        SingleLineTextInput:
            id: txt_username

        CustomLabel:
        	text: 'Password'
        	text_size: self.size
        	valign: 'middle'

        SingleLineTextInput:
            id: txt_password

        CustomLabel:
        	text: 'Email'
        	text_size: self.size
        	valign: 'middle'

        SingleLineTextInput:
            id: txt_email

        GreenButton:
            text: 'Ok'
            on_press: root.insert_data()


        GreenButton:
            text: 'Cancel'
            on_press: app.stop()